name: Bunnyshell - Delete Preview Environment
concurrency: bns-delete-${{ github.event.number || github.event.issue.number }}
on:
  pull_request_target:
    types: [closed]
    branches:
      - '*'
  issue_comment:
    types: [ created, edited ]
permissions:
  pull-requests: write
jobs:
  delete:
    name: Delete Environment
    uses: bunnyshell/workflows/.github/workflows/delete-env.yaml@v2
    with:
      project-id: 2brqgVOXvp
      pr-number: ${{ github.event.number || github.event.issue.number }}
      allowed-users: "*"
      comment-on-pr: true
    secrets:
      bunnyshell-access-token: ${{ secrets.BUNNYSHELL_TOKEN }}
